#!/bin/bash

ROOT=$(dirname $(dirname $0))
BUNDLE=$PWD/bundle

(
  cd $ROOT
  bundle install --binstubs $BUNDLE/bin --path $BUNDLE/vendor
)

for proto in $ROOT/proto/*.proto; do
    n=$(basename $proto | sed -e 's/protocol\([0-9]\+\).proto/\1/')

    (
        set -e
        export BEEFCAKE_NAMESPACE="FFWD::Protocol${n}"
        export PATH="$BUNDLE/bin:$PATH"
        protoc --beefcake_out $ROOT/lib/ffwd $proto
    )

    if [[ $? -ne 0 ]]; then
        echo "Failed to generate: ${proto}"
        exit 1
    fi
done

exit 0
