#!/bin/bash

ROOT=$(dirname $(dirname $0))
BUNDLE=$PWD/bundle

(
  cd $ROOT
  bundle install --binstubs $BUNDLE/bin --path $BUNDLE/vendor
)

for proto in $ROOT/proto/*.proto; do
    $BUNDLE/bin/rprotoc --out $ROOT/lib/ffwd $proto
done
