#!/bin/bash

main() {
    root=$1
    bundle_path=$root/vendor/bundle
    status=0

    while read -u 3 gemfile; do
        dir=$(dirname $gemfile)

        if [[ ! -d $dir/spec ]]; then
            continue
        fi

        echo "Running specs in: $dir"

        (
            cd $dir
            bundle install --path $bundle_path

            if ! bundle exec rspec; then
                status=1
            fi
        )
    done 3< <(find $root -name vendor -prune -o -type f -name Gemfile -print)

    if [[ $status -eq 0 ]]; then
        echo "Tests SUCCESSFUL!"
    else
        echo "Tests FAILED!" >&2
    fi

    return $status
}

root=$(dirname $(dirname $0))
unset BUNDLE_GEMFILE
main "$root"
exit $?
