#!/bin/bash

main() {
    root=$1
    bundle_path=$root/vendor/bundle
    status=0

    if [[ -d $bundle_path ]]; then
        echo "# WARNING: $bundle_path exists!"
    fi

    (
        set -e
        echo "# core: Testing FFWD"
        bundle install --path $bundle_path
        bundle exec rspec

        echo "# core: Installing FFWD for plugins"
        rm -f $root/*.gem

        bundle exec gem build $root/ffwd.gemspec
        bundle exec gem install --no-rdoc --no-ri $root/ffwd-*.gem
        exit 0
    )

    if [[ $? -ne 0 ]]; then
        echo "# core: testing failed"
        return 1
    fi

    while read -u 3 gemfile; do
        dir=$(dirname $gemfile)

        if [[ ! -d $dir/spec ]]; then
            echo "# $dir: no specs... :("
            continue
        fi

        echo "# $dir: specs found! :)"

        (
            set -e
            cd $dir
            bundle install --path $bundle_path
            bundle exec rspec
            exit 0
        )

        status=$?
    done 3< <(find $root/plugins -name vendor -prune -o -type f -name Gemfile -print)

    if [[ $status -eq 0 ]]; then
        echo "Tests SUCCESSFUL!"
    else
        echo "Tests FAILED!" >&2
    fi

    return $status
}

root=$(readlink -f $(dirname $(dirname $0)))
unset BUNDLE_GEMFILE
main "$root"
exit $?
