#!/bin/bash

bundle=$PWD/vendor/bundle
exit_status=0

bundle install --path $bundle

if ! bundle exec rspec; then
    exit_status=1
fi

while read -u 3 gemfile; do
    dir=$(dirname $gemfile)

    if [[ ! -d $dir/spec ]]; then
        continue
    fi

    echo "Running specs in: $dir"

    (
        cd $dir
        bundle install --path $bundle

        if ! bundle exec rspec; then
            exit_status=1
        fi
    )
done 3< <(find plugins -name Gemfile)

if [[ $exit_status -eq 0 ]]; then
    echo "Tests SUCCESSFUL!"
else
    echo "Tests FAILED!" >&2
fi

exit $exit_status
