### Generated by rprotoc. DO NOT EDIT!
### <proto file: ./plugins/ffwd-protobuf/proto/protocol0.proto>
# package FFWD.Protocol0;
# 
# message Metric {
#   // processor to use for metric.
#   optional string proc = 1;
#   // time in ms when metric was generated.
#   optional int64 time = 2;
#   // key of metric.
#   optional string key = 3;
#   // value of metric.
#   optional double value = 4;
#   // host where metric originated.
#   optional string host = 5;
#   // tags associated to metric.
#   repeated string tags = 6;
#   // attributes associated to metric.
#   repeated Attribute attributes = 7;
# }
# 
# message Event {
#   // time in ms when the event was generated.
#   optional int64 time = 1;
#   // key of event.
#   optional string key = 2;
#   // value of event.
#   optional double value = 3;
#   // host where event originated.
#   optional string host = 4;
#   // indicated state of this event.
#   optional string state = 5;
#   // description of event.
#   optional string description = 6;
#   // time this event should be considered valid in seconds.
#   optional int64 ttl = 7;
#   // tags associated to event.
#   repeated string tags = 8;
#   // attributes associated to event.
#   repeated Attribute attributes = 9;
# }
# 
# message Attribute {
#   required string key = 1;
#   optional string value = 2;
# }
# 
# message Message {
#   optional Metric metric = 1;
#   optional Event event = 2;
# }

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module FFWD
  module Protocol0
    class Metric < ::Protobuf::Message
      defined_in __FILE__
      optional :string, :proc, 1
      optional :int64, :time, 2
      optional :string, :key, 3
      optional :double, :value, 4
      optional :string, :host, 5
      repeated :string, :tags, 6
      repeated :Attribute, :attributes, 7
    end
    class Event < ::Protobuf::Message
      defined_in __FILE__
      optional :int64, :time, 1
      optional :string, :key, 2
      optional :double, :value, 3
      optional :string, :host, 4
      optional :string, :state, 5
      optional :string, :description, 6
      optional :int64, :ttl, 7
      repeated :string, :tags, 8
      repeated :Attribute, :attributes, 9
    end
    class Attribute < ::Protobuf::Message
      defined_in __FILE__
      required :string, :key, 1
      optional :string, :value, 2
    end
    class Message < ::Protobuf::Message
      defined_in __FILE__
      optional :Metric, :metric, 1
      optional :Event, :event, 2
    end
  end
end